CREATE TABLE users(
id INT(6) UNSIGNED AUTO_INCREMENT,
email VARCHAR(128) NOT NULL,
passwords VARCHAR(128) NOT NULL,
url_page VARCHAR(30) NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id, url_page)
);

CREATE TABLE links(
link_id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
user_id INT(6) NOT NULL,
image_url VARCHAR(128) NOT NULL,
customer_url VARCHAR(255) NOT NULL,
title VARCHAR(128) NOT NULL,
description TEXT NOT NULL,
active boolean NOT NULL default 1,
last_update datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);